from selenium import selenium
import unittest, time, re

from env import *

#(Total: 36)
#Run2.CloneRun related test cases (total: 36)
import Run2.CloneRun.tc_ID84482_CloneSingleRunWithCancelBtn, Run2.CloneRun.tc_ID84483_CloneSingleRunWithInvalidDefTester, Run2.CloneRun.tc_ID84484_CloneSingleRunWithInvalidManager, Run2.CloneRun.tc_ID84485_CloneSingleRunWithOriginalSummary, Run2.CloneRun.tc_ID84486_CloneSingleRunWithNewSummary, Run2.CloneRun.tc_ID84487_CloneSingleRunWithNewProduct, Run2.CloneRun.tc_ID84488_CloneSingleRunWithoutBuild, Run2.CloneRun.tc_ID84489_CloneSingleRunWithNewProdversion, Run2.CloneRun.tc_ID84490_CloneSingleRunWithNewBuild, Run2.CloneRun.tc_ID84491_CloneSingleRunWithNewDefTester, Run2.CloneRun.tc_ID84492_CloneSingleRunWithoutDefTester, Run2.CloneRun.tc_ID84493_CloneSingleRunWithoutManager, Run2.CloneRun.tc_ID84494_CloneSingleRunWithNewManager, Run2.CloneRun.tc_ID84495_CloneSingleRunWithNewEstTime, Run2.CloneRun.tc_ID84496_CloneSingleRunWithNewNotes, Run2.CloneRun.tc_ID84497_CloneSingleRunWithoutNotes, Run2.CloneRun.tc_ID84501_CloneSingleRunWithLessCase, Run2.CloneRun.tc_ID84502_CloneSingleRunWithoutCase, Run2.CloneRun.tc_ID84506_CloneMultiRunWithCC, Run2.CloneRun.tc_ID84507_CloneMultiRunWithDefAssignee, Run2.CloneRun.tc_ID84508_CloneMultiRunWithDefManager, Run2.CloneRun.tc_ID84509_CloneMultiRunWithDefTester, Run2.CloneRun.tc_ID84511_CloneMultiRunWithInvalidNewManagerAndUpd, Run2.CloneRun.tc_ID84513_CloneMultiRunWithNewAssigneeAndUpd, Run2.CloneRun.tc_ID84514_CloneMultiRunWithNewManagerAndUpd, Run2.CloneRun.tc_ID84515_CloneMultiRunWithNewTesterAndUpd, Run2.CloneRun.tc_ID84516_CloneMultiRunWithTag, Run2.CloneRun.tc_ID84518_CloneMultiRunWithoutCC, Run2.CloneRun.tc_ID84519_CloneMultiRunWithoutTag, Run2.CloneRun.tc_ID84522_CloneMultiRunWithDefAssigneeAndUpd, Run2.CloneRun.tc_ID84523_CloneMultiRunWithDefManagerAndUpd, Run2.CloneRun.tc_ID84524_CloneMultiRunWithDefTesterAndUpd, Run2.CloneRun.tc_ID84525_CloneMultiRunWithNewAssigneeButNotUpd, Run2.CloneRun.tc_ID84526_CloneMultiRunWithNewManagerButNotUpd, Run2.CloneRun.tc_ID84527_CloneMultiRunWithNewTesterButNotUpd, Run2.CloneRun.tc_ID84647_CloneMyRun

def suite():

	suite = unittest.TestSuite()

	#Run2.CloneRun related test cases (total: 36)
	suite.addTest(Run2.CloneRun.tc_ID84482_CloneSingleRunWithCancelBtn.CloneSingleRunWithCancelBtn("test_CloneSingleRunWithCancelBtn"))
	suite.addTest(Run2.CloneRun.tc_ID84483_CloneSingleRunWithInvalidDefTester.CloneSingleRunWithInvalidDefTester("test_CloneSingleRunWithInvalidDefTester"))
	suite.addTest(Run2.CloneRun.tc_ID84484_CloneSingleRunWithInvalidManager.CloneSingleRunWithInvalidManager("test_CloneSingleRunWithInvalidManager"))
	suite.addTest(Run2.CloneRun.tc_ID84485_CloneSingleRunWithOriginalSummary.CloneSingleRunWithOriginalSummary("test_CloneSingleRunWithOriginalSummary"))
	suite.addTest(Run2.CloneRun.tc_ID84486_CloneSingleRunWithNewSummary.CloneSingleRunWithNewSummary("test_CloneSingleRunWithNewSummary"))
	suite.addTest(Run2.CloneRun.tc_ID84487_CloneSingleRunWithNewProduct.CloneSingleRunWithNewProduct("test_CloneSingleRunWithNewProduct"))
	suite.addTest(Run2.CloneRun.tc_ID84488_CloneSingleRunWithoutBuild.CloneSingleRunWithoutBuild("test_CloneSingleRunWithoutBuild"))
	suite.addTest(Run2.CloneRun.tc_ID84489_CloneSingleRunWithNewProdversion.CloneSingleRunWithNewProdversion("test_CloneSingleRunWithNewProdversion"))
	suite.addTest(Run2.CloneRun.tc_ID84490_CloneSingleRunWithNewBuild.CloneSingleRunWithNewBuild("test_CloneSingleRunWithNewBuild"))
	suite.addTest(Run2.CloneRun.tc_ID84491_CloneSingleRunWithNewDefTester.CloneSingleRunWithNewDefTester("test_CloneSingleRunWithNewDefTester"))
	suite.addTest(Run2.CloneRun.tc_ID84492_CloneSingleRunWithoutDefTester.CloneSingleRunWithoutDefTester("test_CloneSingleRunWithoutDefTester"))
	suite.addTest(Run2.CloneRun.tc_ID84493_CloneSingleRunWithoutManager.CloneSingleRunWithoutManager("test_CloneSingleRunWithoutManager"))
	suite.addTest(Run2.CloneRun.tc_ID84494_CloneSingleRunWithNewManager.CloneSingleRunWithNewManager("test_CloneSingleRunWithNewManager"))
	suite.addTest(Run2.CloneRun.tc_ID84495_CloneSingleRunWithNewEstTime.CloneSingleRunWithNewEstTime("test_CloneSingleRunWithNewEstTime"))
	suite.addTest(Run2.CloneRun.tc_ID84496_CloneSingleRunWithNewNotes.CloneSingleRunWithNewNotes("test_CloneSingleRunWithNewNotes"))
	suite.addTest(Run2.CloneRun.tc_ID84497_CloneSingleRunWithoutNotes.CloneSingleRunWithoutNotes("test_CloneSingleRunWithoutNotes"))
	suite.addTest(Run2.CloneRun.tc_ID84501_CloneSingleRunWithLessCase.CloneSingleRunWithLessCase("test_CloneSingleRunWithLessCase"))
	suite.addTest(Run2.CloneRun.tc_ID84502_CloneSingleRunWithoutCase.CloneSingleRunWithoutCase("test_CloneSingleRunWithoutCase"))
	suite.addTest(Run2.CloneRun.tc_ID84506_CloneMultiRunWithCC.CloneMultiRunWithCC("test_CloneMultiRunWithCC"))
	suite.addTest(Run2.CloneRun.tc_ID84507_CloneMultiRunWithDefAssignee.CloneMultiRunWithDefAssignee("test_CloneMultiRunWithDefAssignee"))
	suite.addTest(Run2.CloneRun.tc_ID84508_CloneMultiRunWithDefManager.CloneMultiRunWithDefManager("test_CloneMultiRunWithDefManager"))
	suite.addTest(Run2.CloneRun.tc_ID84509_CloneMultiRunWithDefTester.CloneMultiRunWithDefTester("test_CloneMultiRunWithDefTester"))
	suite.addTest(Run2.CloneRun.tc_ID84511_CloneMultiRunWithInvalidNewManagerAndUpd.CloneMultiRunWithInvalidNewManagerAndUpd("test_CloneMultiRunWithInvalidNewManagerAndUpd"))
	suite.addTest(Run2.CloneRun.tc_ID84513_CloneMultiRunWithNewAssigneeAndUpd.CloneMultiRunWithNewAssigneeAndUpd("test_CloneMultiRunWithNewAssigneeAndUpd"))
	suite.addTest(Run2.CloneRun.tc_ID84514_CloneMultiRunWithNewManagerAndUpd.CloneMultiRunWithNewManagerAndUpd("test_CloneMultiRunWithNewManagerAndUpd"))
	suite.addTest(Run2.CloneRun.tc_ID84515_CloneMultiRunWithNewTesterAndUpd.CloneMultiRunWithNewTesterAndUpd("test_CloneMultiRunWithNewTesterAndUpd"))
	suite.addTest(Run2.CloneRun.tc_ID84516_CloneMultiRunWithTag.CloneMultiRunWithTag("test_CloneMultiRunWithTag"))
	suite.addTest(Run2.CloneRun.tc_ID84518_CloneMultiRunWithoutCC.CloneMultiRunWithoutCC("test_CloneMultiRunWithoutCC"))
	suite.addTest(Run2.CloneRun.tc_ID84519_CloneMultiRunWithoutTag.CloneMultiRunWithoutTag("test_CloneMultiRunWithoutTag"))
	suite.addTest(Run2.CloneRun.tc_ID84522_CloneMultiRunWithDefAssigneeAndUpd.CloneMultiRunWithDefAssigneeAndUpd("test_CloneMultiRunWithDefAssigneeAndUpd"))
	suite.addTest(Run2.CloneRun.tc_ID84523_CloneMultiRunWithDefManagerAndUpd.CloneMultiRunWithDefManagerAndUpd("test_CloneMultiRunWithDefManagerAndUpd"))
	suite.addTest(Run2.CloneRun.tc_ID84524_CloneMultiRunWithDefTesterAndUpd.CloneMultiRunWithDefTesterAndUpd("test_CloneMultiRunWithDefTesterAndUpd"))
	suite.addTest(Run2.CloneRun.tc_ID84525_CloneMultiRunWithNewAssigneeButNotUpd.CloneMultiRunWithNewAssigneeButNotUpd("test_CloneMultiRunWithNewAssigneeButNotUpd"))
	suite.addTest(Run2.CloneRun.tc_ID84526_CloneMultiRunWithNewManagerButNotUpd.CloneMultiRunWithNewManagerButNotUpd("test_CloneMultiRunWithNewManagerButNotUpd"))
	suite.addTest(Run2.CloneRun.tc_ID84527_CloneMultiRunWithNewTesterButNotUpd.CloneMultiRunWithNewTesterButNotUpd("test_CloneMultiRunWithNewTesterButNotUpd"))
	suite.addTest(Run2.CloneRun.tc_ID84647_CloneMyRun.CloneMyRun("test_CloneMyRun"))

	return suite

if __name__ == "__main__":   unittest.main(defaultTest = 'suite')