from selenium import selenium
import unittest, time, re

from env import *

#(Total: 46)
#CreateRun related test cases (total: 31)
import CreateRun.tc_ID107867_SelectNoCaseToCreateRun, CreateRun.tc_ID84564_AddBlankProdVerFromCreateRun, CreateRun.tc_ID84565_AddBuildWithBlankNameFromCreateRun, CreateRun.tc_ID84566_AddBuildWithDescFromCreateRun, CreateRun.tc_ID84567_AddBuildWithExistingNameFromCreateRun, CreateRun.tc_ID84568_AddBuildWithNewProdFromCreateRun, CreateRun.tc_ID84569_AddBuildWithOtherProdFromCreateRun, CreateRun.tc_ID84571_AddBuildFromCreateRun, CreateRun.tc_ID84572_AddProductFromCreateRun, CreateRun.tc_ID84573_AddProdVerFromCreateRun, CreateRun.tc_ID84574_AddProdVerWithOtherProdFromCreateRun, CreateRun.tc_ID84575_CreateRunByChangeProduct, CreateRun.tc_ID84576_CreateRunByChangeProdVer, CreateRun.tc_ID84577_CreateRunByChangeRunManager, CreateRun.tc_ID84578_CreateRunByChangeBuild, CreateRun.tc_ID84581_CreateRunWithoutDefTester, CreateRun.tc_ID84582_CreateRunWithoutSummary, CreateRun.tc_ID84583_CreateRunWithDefTester, CreateRun.tc_ID84584_CreateRunWithRunManager, CreateRun.tc_ID84585_CreateRunWithInvalidDefTester, CreateRun.tc_ID84586_CreateRunWithInvalidRunManager, CreateRun.tc_ID84587_CreateRunWithLongNotes, CreateRun.tc_ID84589_CreateRunWithNotes, CreateRun.tc_ID84590_CreateRunByAddEnvironment, CreateRun.tc_ID84592_CreateRunByEditEstimatedTime, CreateRun.tc_ID84595_OrderCaseByCategoryInCreateRun, CreateRun.tc_ID84596_OrderCaseByCreatedDateInCreateRun, CreateRun.tc_ID84597_OrderCaseByPriorityInCreateRun, CreateRun.tc_ID84598_OrderCaseBySummaryInCreateRun, CreateRun.tc_ID84599_CreateRunWithoutCase, CreateRun.tc_ID84601_RemoveCaseInCreateRun

#Others related test cases (total: 15)
import Others.tc_ID107475_ChangeCategoryForCasesInPlan, Others.tc_ID107479_CheckAttachListInCase, Others.tc_ID107480_DeleteAttachmentInCase, Others.tc_ID107482_DeleteAttachmentInPlan, Others.tc_ID107486_CheckOptionRemainedAfterReport, Others.tc_ID107788_CloneSingleRunWithFilteredCaseRun, Others.tc_ID107796_CloneSingleRunWithReserveOpt, Others.tc_ID107822_AddCasesToRun, Others.tc_ID107827_DeleteEnvironmentGroup, Others.tc_ID107860_ChangeCategoryWithoutCaseInPlan, Others.tc_ID116310_EditRemovePropertyInRun, Others.tc_ID84375_RemoveInvalidChildNode, Others.tc_ID84654_DisableEnvironmentGroup, Others.tc_ID87491_SearchCaseByOverCreateTimeInASearch, Others.tc_ID87505_SearchRunBySingleMultiStatus

def suite():

	suite = unittest.TestSuite()

	#CreateRun related test cases (total: 31)
	suite.addTest(CreateRun.tc_ID107867_SelectNoCaseToCreateRun.SelectNoCaseToCreateRun("test_SelectNoCaseToCreateRun"))
	suite.addTest(CreateRun.tc_ID84564_AddBlankProdVerFromCreateRun.AddBlankProdVerFromCreateRun("test_AddBlankProdVerFromCreateRun"))
	suite.addTest(CreateRun.tc_ID84565_AddBuildWithBlankNameFromCreateRun.AddBuildWithBlankNameFromCreateRun("test_AddBuildWithBlankNameFromCreateRun"))
	suite.addTest(CreateRun.tc_ID84566_AddBuildWithDescFromCreateRun.AddBuildWithDescFromCreateRun("test_AddBuildWithDescFromCreateRun"))
	suite.addTest(CreateRun.tc_ID84567_AddBuildWithExistingNameFromCreateRun.AddBuildWithExistingNameFromCreateRun("test_AddBuildWithExistingNameFromCreateRun"))
	suite.addTest(CreateRun.tc_ID84568_AddBuildWithNewProdFromCreateRun.AddBuildWithNewProdFromCreateRun("test_AddBuildWithNewProdFromCreateRun"))
	suite.addTest(CreateRun.tc_ID84569_AddBuildWithOtherProdFromCreateRun.AddBuildWithOtherProdFromCreateRun("test_AddBuildWithOtherProdFromCreateRun"))
	suite.addTest(CreateRun.tc_ID84571_AddBuildFromCreateRun.AddBuildFromCreateRun("test_AddBuildFromCreateRun"))
	suite.addTest(CreateRun.tc_ID84572_AddProductFromCreateRun.AddProductFromCreateRun("test_AddProductFromCreateRun"))
	suite.addTest(CreateRun.tc_ID84573_AddProdVerFromCreateRun.AddProdVerFromCreateRun("test_AddProdVerFromCreateRun"))
	suite.addTest(CreateRun.tc_ID84574_AddProdVerWithOtherProdFromCreateRun.AddProdVerWithOtherProdFromCreateRun("test_AddProdVerWithOtherProdFromCreateRun"))
	suite.addTest(CreateRun.tc_ID84575_CreateRunByChangeProduct.CreateRunByChangeProduct("test_CreateRunByChangeProduct"))
	suite.addTest(CreateRun.tc_ID84576_CreateRunByChangeProdVer.CreateRunByChangeProdVer("test_CreateRunByChangeProdVer"))
	suite.addTest(CreateRun.tc_ID84577_CreateRunByChangeRunManager.CreateRunByChangeRunManager("test_CreateRunByChangeRunManager"))
	suite.addTest(CreateRun.tc_ID84578_CreateRunByChangeBuild.CreateRunByChangeBuild("test_CreateRunByChangeBuild"))
	suite.addTest(CreateRun.tc_ID84581_CreateRunWithoutDefTester.CreateRunWithoutDefTester("test_CreateRunWithoutDefTester"))
	suite.addTest(CreateRun.tc_ID84582_CreateRunWithoutSummary.CreateRunWithoutSummary("test_CreateRunWithoutSummary"))
	suite.addTest(CreateRun.tc_ID84583_CreateRunWithDefTester.CreateRunWithDefTester("test_CreateRunWithDefTester"))
	suite.addTest(CreateRun.tc_ID84584_CreateRunWithRunManager.CreateRunWithRunManager("test_CreateRunWithRunManager"))
	suite.addTest(CreateRun.tc_ID84585_CreateRunWithInvalidDefTester.CreateRunWithInvalidDefTester("test_CreateRunWithInvalidDefTester"))
	suite.addTest(CreateRun.tc_ID84586_CreateRunWithInvalidRunManager.CreateRunWithInvalidRunManager("test_CreateRunWithInvalidRunManager"))
	suite.addTest(CreateRun.tc_ID84587_CreateRunWithLongNotes.CreateRunWithLongNotes("test_CreateRunWithLongNotes"))
	suite.addTest(CreateRun.tc_ID84589_CreateRunWithNotes.CreateRunWithNotes("test_CreateRunWithNotes"))
	suite.addTest(CreateRun.tc_ID84590_CreateRunByAddEnvironment.CreateRunByAddEnvironment("test_CreateRunByAddEnvironment"))
	suite.addTest(CreateRun.tc_ID84592_CreateRunByEditEstimatedTime.CreateRunByEditEstimatedTime("test_CreateRunByEditEstimatedTime"))
	suite.addTest(CreateRun.tc_ID84595_OrderCaseByCategoryInCreateRun.OrderCaseByCategoryInCreateRun("test_OrderCaseByCategoryInCreateRun"))
	suite.addTest(CreateRun.tc_ID84596_OrderCaseByCreatedDateInCreateRun.OrderCaseByCreatedDateInCreateRun("test_OrderCaseByCreatedDateInCreateRun"))
	suite.addTest(CreateRun.tc_ID84597_OrderCaseByPriorityInCreateRun.OrderCaseByPriorityInCreateRun("test_OrderCaseByPriorityInCreateRun"))
	suite.addTest(CreateRun.tc_ID84598_OrderCaseBySummaryInCreateRun.OrderCaseBySummaryInCreateRun("test_OrderCaseBySummaryInCreateRun"))
	suite.addTest(CreateRun.tc_ID84599_CreateRunWithoutCase.CreateRunWithoutCase("test_CreateRunWithoutCase"))
	suite.addTest(CreateRun.tc_ID84601_RemoveCaseInCreateRun.RemoveCaseInCreateRun("test_RemoveCaseInCreateRun"))

	#Others related test cases (total: 15)
	suite.addTest(Others.tc_ID107475_ChangeCategoryForCasesInPlan.ChangeCategoryForCasesInPlan("test_ChangeCategoryForCasesInPlan"))
	suite.addTest(Others.tc_ID107479_CheckAttachListInCase.CheckAttachListInCase("test_CheckAttachListInCase"))
	suite.addTest(Others.tc_ID107480_DeleteAttachmentInCase.DeleteAttachmentInCase("test_DeleteAttachmentInCase"))
	suite.addTest(Others.tc_ID107482_DeleteAttachmentInPlan.DeleteAttachmentInPlan("test_DeleteAttachmentInPlan"))
	suite.addTest(Others.tc_ID107486_CheckOptionRemainedAfterReport.CheckOptionRemainedAfterReport("test_CheckOptionRemainedAfterReport"))
	suite.addTest(Others.tc_ID107788_CloneSingleRunWithFilteredCaseRun.CloneSingleRunWithFilteredCaseRun("test_CloneSingleRunWithFilteredCaseRun"))
	suite.addTest(Others.tc_ID107796_CloneSingleRunWithReserveOpt.CloneSingleRunWithReserveOpt("test_CloneSingleRunWithReserveOpt"))
	suite.addTest(Others.tc_ID107822_AddCasesToRun.AddCasesToRun("test_AddCasesToRun"))
	suite.addTest(Others.tc_ID107827_DeleteEnvironmentGroup.DeleteEnvironmentGroup("test_DeleteEnvironmentGroup"))
	suite.addTest(Others.tc_ID107860_ChangeCategoryWithoutCaseInPlan.ChangeCategoryWithoutCaseInPlan("test_ChangeCategoryWithoutCaseInPlan"))
	suite.addTest(Others.tc_ID116310_EditRemovePropertyInRun.EditRemovePropertyInRun("test_EditRemovePropertyInRun"))
	suite.addTest(Others.tc_ID84375_RemoveInvalidChildNode.RemoveInvalidChildNode("test_RemoveInvalidChildNode"))
	suite.addTest(Others.tc_ID84654_DisableEnvironmentGroup.DisableEnvironmentGroup("test_DisableEnvironmentGroup"))
	suite.addTest(Others.tc_ID87491_SearchCaseByOverCreateTimeInASearch.SearchCaseByOverCreateTimeInASearch("test_SearchCaseByOverCreateTimeInASearch"))
	suite.addTest(Others.tc_ID87505_SearchRunBySingleMultiStatus.SearchRunBySingleMultiStatus("test_SearchRunBySingleMultiStatus"))

	return suite

if __name__ == "__main__":
   unittest.main(defaultTest = 'suite')
